# Farve ----------------------------------------------------------------------------------------------------------------

TabelFarveFG_V   <- "#398FCC"
TabelFarveBG_V   <- "#E4F0F8"
TabelFarveKant_V <- "#808080"

# Ikon -----------------------------------------------------------------------------------------------------------------

# Findes OGSÅ i InputData_V
IkonPingPong_V    <- "<iconify-icon icon=mdi:table-tennis style=color:#398FCC></iconify-icon>"
IkonFest_V        <- "<iconify-icon icon=mdi:party-popper style=color:#F1C40F></iconify-icon>"
IkonGentagelse_V  <- "<iconify-icon icon=mdi:autorenew></iconify-icon>"

# Findes IKKE i InputData_V
IkonGlobus_V       <- "<iconify-icon icon=mdi:earth></iconify-icon>"
IkonPerson_V       <- "<iconify-icon icon=mdi:account></iconify-icon>"
IkonBogmærke_V     <- "<iconify-icon icon=mdi:bookmark-plus style=color:#F1C40F></iconify-icon>"
IkonWindows_V      <- "<iconify-icon icon=mdi:microsoft-windows></iconify-icon>"
IkonMac_V          <- "<iconify-icon icon=mdi:apple></iconify-icon>"
IkonFødt_V         <- "<iconify-icon icon=mdi:cake-variant></iconify-icon>"
IkonNul_V          <- "<iconify-icon icon=mdi:numeric-0-circle></iconify-icon>"
IkonIndbydelse_V   <- "<iconify-icon icon=mdi:text-box-outline></iconify-icon>"
IkonTimeglas_V     <- "<iconify-icon icon=mdi:timer-sand></iconify-icon>"
IkonRegler_V       <- "<iconify-icon icon=mdi:scale-balance></iconify-icon>"
IkonKoncept_V      <- "<iconify-icon icon=mdi:bullseye-arrow></iconify-icon>"
IkonLinkNy_V       <- "<iconify-icon icon=mdi:open-in-new></iconify-icon>"
IkonPenge_V        <- "<iconify-icon icon=mdi:cash></iconify-icon>"
IkonRefusion_V     <- "<iconify-icon icon=mdi:cash-refund></iconify-icon>"
IkonForplejning_V  <- "<iconify-icon icon=mdi:food-fork-drink></iconify-icon>"
IkonParkering_V    <- "<iconify-icon icon=mdi:parking></iconify-icon>"
IkonTransport_V    <- "<iconify-icon icon=mdi:train-car></iconify-icon>"
IkonMedbring_V     <- "<iconify-icon icon=mdi:bag-personal></iconify-icon>"
IkonOvernatning_V  <- "<iconify-icon icon=mdi:bed></iconify-icon>"
IkonPokal_V        <- "<iconify-icon icon=mdi:trophy></iconify-icon>"
IkonGave_V         <- "<iconify-icon icon=mdi:gift></iconify-icon>"
IkonHåndNed_V      <- "<iconify-icon icon=mdi:hand-pointing-down></iconify-icon>"
IkonLokation_V     <- "<iconify-icon icon=mdi:pin></iconify-icon>"
IkonMail_V         <- "<iconify-icon icon=mdi:email></iconify-icon>"
IkonTelefon_V      <- "<iconify-icon icon=mdi:phone></iconify-icon>"
IkonGraf_V         <- "<iconify-icon icon=mdi:chart-box></iconify-icon>"
IkonBillet_V       <- "<iconify-icon icon=mdi:tags></iconify-icon>"
IkonPilOpVenstre_V <- "<iconify-icon icon=mdi:arrow-up-left></iconify-icon>"
IkonFacebook_V     <- "<span class=bi-facebook style=color:#1877F2;font-size:18px></span>"
IkonMessenger_V    <- "<span class=bi-messenger style=color:#0695FF;font-size:18px></span>"
IkonGitHub_V       <- "<span class=bi-github style=color:#9F7BE1;font-size:18px></span>"